/**
 * Per-profile object-position overrides for photos that don't display well
 * with the default `center center` anchor.
 *
 * Key: slug generated by createSlug(profile.name)
 * Value: CSS object-position value (e.g. 'center top', 'center 20%', '50% 15%')
 *
 * Use 'center top'  → face is in the upper portion of the photo
 * Use 'center 30%'  → face is slightly below the very top
 * Use 'center'      → face is perfectly centred (the global default — no entry needed)
 */
export const PHOTO_POSITION_OVERRIDES: Record<string, string> = {
  'ommsharravana':               'center top',
  'purushothaman-elango':        'center top',
  'r-praveen-kumar':             'center top',
  'r-ramesh-krishnan':           'center top',
  'srinivasan-n':                'center top',
  'tom-jogy':                    'center top',
  'vairavan-subramanian':        'center top',
  'varadharajulu-chandrasekaran':'center top',
};

/** Returns the objectPosition for a given slug, or the default 'center'. */
export function getPhotoPosition(slug: string): string {
  return PHOTO_POSITION_OVERRIDES[slug] ?? 'center';
}
